language: java
jdk: oraclejdk11
services:
  - postgresql
  - docker
before_script:
  - psql -c 'create database webmonere_main;' -U postgres
before_install:
  - chmod +x mvnw
  - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
install: true
script:
  - ./mvnw clean package
  - docker build -t schedule-service .
  - docker run -e "$DB_URl" -e "$DB_USER" -e "$DB_PASS"  -p 5000:8080 schedule-service


