language: java
jdk: oraclejdk11
services:
  - postgresql
  - docker
before_script:
  - psql -c 'create database webmonere_main;' -U postgres
before_install:
  - chmod +x mvnw
  - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
install: true
script:
  - $ ./mvnw clean install dockerfile:build

