spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: "jdbc:postgresql://localhost:5432/webmonere_main"
    username: ${DB_USER}
    password: ${DB_PASS}

