spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

